spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: Bank
        hbm2ddl.auto: validate
  datasource:
    username: postgres
    password: masterkey
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: Bank
logging:
  file:
    name: log.log
    path: /
  level:
    root: info