iban:
  country: BY
  countryDigits: 1134
  bank: VAKO
  bankDigits: 31102024
card.bin: 12049
db.schema: bank
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        default_schema: ${db.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    username: postgres
    password: masterkey
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${db.schema}
  liquibase:
    default-schema: ${db.schema}
logging:
  file:
    name: log.log
    path: /
  level:
    root: info
app.image.bucket: /Users/vadim/IdeaProjects/bank/avatars